### ISSUE TITLE
A few potential issues

### ISSUE THREAD

**Issue by isty2e** [mkinfrared/baldurs-gate3-mod-manager#33] opened 2023-10-07 23:32 UTC
## Summary

I am not sure if it is just me, but I am having trouble what is happening and how I can resolve. Though I have little experience in running electron apps from source code, but if some instructions are given, I am willing to provide some debug logs or run the app with monkeypatches. 

### Activate button missing

<img width="1136" alt="bg3_mm_screenshot" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/571680/0612390c-5e6c-4d65-a9ba-62cb31607af2">

I expected activate button sitting around somewhere in installed mods pane, but it is nowhere to be found.

### modesettings.lsx is not modified

`~/Documents/Larian Studios/Baldur's Gate 3/PlayerProfiles/Public/modsettings.lsx` is expected to be changed upon mod installation/activation, but it remains unchanged. This has nothing to do with bg3 overwriting it, since it happens without running the game. I do see `const saveModSettings(content: string)` in the code, which is supposed to do this, but somehow it seems like it is not working as intended.

**Comment by mkinfrared** [comment] 2023-10-08 07:09
Duplicate of #32

**Comment by mkinfrared** [comment] 2023-10-08 07:13
as I mentioned there, the mods you installed don't have `info.json` file, so there's nothing to activate. I will remove that button in the future as it only confuses people. It doesn't do what it was supposed to do. I haven't yet found any Larian's description on how to install mods. Only thanks to some guy from reddit who posted a proper description on how to install mods on mac I was able to install my own.

**Comment by isty2e** [comment] 2023-10-08 07:18
Thanks for the answer! Some of the mods I have installed are not working, so I suspected it might be due to the lsx file, but it would seem that the problem lies elsewhere. Closing the issue.

**Comment by mkinfrared** [comment] 2023-10-08 07:22
Try to address the issue on the mods page. I guess most of the authors only support Windows only and don’t test it on macs. I remember I couldn’t make a dice mod work, though it was before I created this app. Probably I will try it again.

**Comment by DIXAK** [comment] 2023-10-08 15:01
> Thanks for the answer! Some of the mods I have installed are not working, so I suspected it might be due to the lsx file, but it would seem that the problem lies elsewhere. Closing the issue.


I think it actually has something to do with the .lsx file. When I copied my modsettings.lsx from Windows to Mac, everything worked fine. 
<img width="1022" alt="Schermafbeelding_2023-10-08_om_16 53 00" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/147284669/f9ad2108-ca30-4e65-92cc-3f0072f40b34">

**Comment by mkinfrared** [comment] 2023-10-08 15:03
can you send me a link to this mod? I will take a look

**Comment by DIXAK** [comment] 2023-10-08 15:07
Of course! <'3

https://www.nexusmods.com/baldursgate3/mods/243?tab=posts&BH=1

**Comment by mkinfrared** [comment] 2023-10-08 15:14
thanks! I see what the problem is. the mods which I tested had the following structure of `info.json`

{
  "Mods": [
    {
      "Author": "Aetherpoint",
      "Name": "BlackDye",
      "Folder": "BlackDye",
      "Version": "268435456",
      "Description": "",
      "UUID": "00000000-0000-0000-0003-xAetherpoint",
      "Created": "2023-08-21T22:47:44.8088068-06:00",
      "Dependencies": [],
      "Group": "31602df9-b025-4c3d-b122-dde90f8d1e1c"
    }
  ],
  "MD5": "18fc4e75538f03ef3ec97d8fd667dd23"
}

nomorespiders has the following structure

{
    "mods": [
    {
        "modName": "nomorespiders",
        "UUID": "be0be8bd-293a-4f5d-976f-31c5f01239d8",
        "folderName": "nomorespiders",
        "version": "1.03",
        "MD5": ""
    }
    ]
}

I anticipated some level of standardization in the way people should share information about the mod. Alright, I will attempt to rectify that discrepancy.

**Closed** 2023-10-08 18:53 UTC
Labels: bug, question
