### ISSUE TITLE
Allow us to add mods by choosing a .pak file instead of a .zip

### ISSUE THREAD

**Issue by ancestral** [mkinfrared/baldurs-gate3-mod-manager#46] opened 2023-10-09 06:03 UTC
When download mods, often they get unzipped and the archive is removed.

Can you allow adding .pak files? You could check the same directory as the .pak file for the presence of an info.json file.

**Comment by mkinfrared** [comment] 2023-11-02 21:03
Duplicate of #70

**Closed** 2023-11-02 22:13 UTC
Labels: enhancement
